force-app/main/default/objects/Mask_Config__c/Mask_Config__c.object-meta.xml
<CustomObject>
    <description>Configuration for Masking data values</description>
    <label>Mask Config</label>
    <nameField>
        <displayFormat>MCONF-{00000}</displayFormat>
        <label>Mask Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mask Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mask_Config__c/fields/Mask__c.field-meta.xml
<CustomField>
    <fullName>Mask__c</fullName>
    <description>The Mask to be used</description>
    <inlineHelpText>The Mask to be used</inlineHelpText>
    <label>Mask</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mask_Config__c/fields/Source_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Name__c</fullName>
    <description>API Name of source field from the source SObject</description>
    <inlineHelpText>API Name of source field from the source SObject</inlineHelpText>
    <label>Source Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mask_Config__c/fields/Source_SObject__c.field-meta.xml
<CustomField>
    <fullName>Source_SObject__c</fullName>
    <description>API Name of Source SObject</description>
    <inlineHelpText>API Name of Source SObject</inlineHelpText>
    <label>Source SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Mask.cls
public with sharing class Mask {
	
    private string sObjName;
    private String[] validFields;
    Map<String,Schema.SObjectField> fieldsMap;
    Map<String,Mask_Config__c> validConfigMap = new Map<string,Mask_Config__c>();
    boolean insertNew = false;
    Schema.SObjectType theSObjectType = null;
    public Mask(String sObjectName,boolean insertNew){
        this.sObjName = sObjectName;
        this.insertNew = insertNew;
        initConfig();
    }
    
    private void initConfig(){
        
        Mask_Config__c[] configRecs = [Select Source_Field_Name__c,Mask__c from Mask_Config__c where Source_SObject__c=:sObjName];
        validFields = new String[]{};
        theSObjectType = Schema.getGlobalDescribe().get(sObjName.toLowerCase());
        fieldsMap = theSObjectType.getDescribe().fields.getMap();
        for(String fieldName: fieldsMap.keySet()){
            Schema.SObjectField theField = fieldsMap.get(fieldName);
            if(theField!=null && theField.getDescribe().isUpdateable() && theField.getDescribe().isCreateable()){
                validFields.add(fieldName);
            }
        }
        Set<String> validFieldSet = new Set<String>(validFields);
        for(Mask_Config__c config: configRecs){
            if(validFieldSet.contains(config.Source_Field_Name__c)){
                validConfigMap.put(config.Source_Field_Name__c,config);
            }
        }
    }
    
    public void execute(){
        SObject[] recordsToUpdate = new SObject[]{};
        fflib_ISObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new List<Schema.SObjectType>{theSObjectType});
        for(SObject myRecord : Database.query('Select '+String.join(validFields,',')+' from '+sObjName)){
            
            for(String fName:validFields){
                if(validConfigMap.containsKey(fName) && isMaskValid(validConfigMap.get(fName).Mask__c)){
                    String maskedVal = Masker.doMask(String.valueOf(myRecord.get(fName)),validConfigMap.get(fName).Mask__c);
                    switch on fieldsMap.get(fName).getDescribe().getType() {
                        when  Boolean{
                            myRecord.put(fName,Boolean.valueOf(maskedVal));
                        }
                        when  Date{
                            myRecord.put(fName,Date.valueOf(maskedVal));
                        }
                        when  Currency{
                            myRecord.put(fName,Decimal.valueOf(maskedVal));
                        }
                        when  Integer{
                            myRecord.put(fName,Integer.valueOf(maskedVal));
                        }
                        when  Long{
                            myRecord.put(fName,Long.valueOf(maskedVal));
                        }
                        when  Percent{
                            myRecord.put(fName,Decimal.valueOf(maskedVal));
                        }
                        when else {
                            myRecord.put(fName,maskedVal);
                        }
                    }
                }
            }
            if(insertNew){
                uow.registerNew(myRecord.clone(false,false,false,false));
            }else{
                uow.registerDirty(myRecord);
            }
        }
        uow.commitWork();
    }
    
    
    private boolean isMaskValid(String theMask){
        return true;
    }
}